spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev
app:
  team-name: hi
  team-size: ${random.uuid}
  team-leader: dev

---
spring:
  config:
    activate:
      on-profile: staging
app:
  team-name: hi
  team-size: ${random.uuid}
  team-leader: staging

---
spring:
  config:
    activate:
      on-profile: prod    
app:
  team-name: hi
  team-size: ${random.uuid}
  team-leader: prod